config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}
  root to: "home#index"

  resources :users, only: :create

  resources  :test, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_test only: %i[index create show destroy]
  before_action :find_question only: %i[show destroy update edit]

  rescue_form ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def new
    @question = @test.questions.new
  end

  def show
    render plain: @question.inspect
  end

  def update
     if @question.update(questions_params)
      redirect_to @question
    else
      render :edit
    end

  end

  def edit

  end

  def create
    question = @test.questions.new(question_params)
    if question.save
      render plain: question.inspect
    else
      render plain: 'The question was not created!'
    end

  end

  def destroy
    @question.destroy
    redirect_to @test
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      'Create question'
    else
      'Edit question'
    end
  end
end

app/views/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= question.test_id %></td>
  <td><%= link_to 'Show', question_path(question) %></td>
  <td><%= link_to 'Edit', edit_question_path(question) %></td>
  <td>
    <%= link_to 'Delete'
                 question_past(question)
                 method: :delete,
                 data: { confirm: 'Are you sure?'} %>
  </td>
</tr>

app/views/questions/show.html.erb
<table>
  <tr>
    <th>Вопрос</th>
    <th>Test ID</th>
    <th colspan="2">Функции</th>
  </tr>

  <%= render @question %>>

  <br>
  <h2>Answers</h2>
  <%= link_to 'New answer', new_question_answer_path(@question) %>
  <%= render @question.answers %>
</table>