config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}
  root to: "home#index"

  resources :users, only: :create

  resources  :test, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord

  SUCCESS_RATE_PERCENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :next_question

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end
    save!
  end

  def count_questions
    self.test.questions.where("id <= ?", current_question.id).count
  end

  def percentage_result
    100.0 / test.questions.count * correct_questions
  end

  def success?
    percentage_result >= SUCCESS_RATE_PERCENT
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/views/test_passages/result.html.erb
<h1>Test: <%= @test_passage.test.title %> был завершен!</h1>

<h2>Result:

<% if @test_passage.success? %>
  <span style="color: green;"><%= @test_passage.percentage_result %>%</span>
<% else %>
  <span style="color: red;"><%= @test_passage.percentage_result %>%</span>
<% end %>

</h2>
<%= link_to "Back", :tests %>

app/views/test_passages/show.html.erb
<h1>Passing the <%=test_passage.test.title %></h1>

<b>
  <%= @test_passage.current_question.body %>
</b>

<p>
  Current question: <%= @test_passage.count_questions %> out of <%= @test_passage.test.questions.count %>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :text, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
    <% end %>

  <p><%= form.submit 'Next' %></p>
<% end %>