config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}
  root to: "home#index"

  resources :users, only: :create

  resources  :test, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  ANSWERS_LIMIT = 4

  belongs_to :question

  scope :true_answer, -> { where(correct: true) }

  validate :validate_answers_volume_questions, on: :create

  def validate_answers_limit_volume_questions
    errors.add('Replies must be less than 4') if question.answers.count >= ANSWERS_LIMIT
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :authenticate_user!
  before_action :find_question, only: %i[ new create ]
  before_action :set_answer, only: %i[ show edit update destroy ]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to @answer.question
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer.question
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question
  end

  private
    def find_question
      @question = Question.find(params[:question_id])
    end

    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:text, :correct)
    end
end

app/views/admin/answers/_answer.html.erb
<li>
   <%= answer.body %><br>
   <%= link_to 'Show', admin_answer_path(answer) %> |
   <%= link_to 'Edit', admin_edit_answer_path(answer) %> |
   <%= link_to 'Delete',
                admin_answer_path(answer),
                method: :delete,
                data: {confirm: 'Are you sure?'} %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
   <%= form.label :text %>
   <%= form.text_area :text, id: :answer_text, rows: 7, cols: 60 %>
 </p>

 <p>
   <%= form.label :correct %>
   <%= form.check_box :correct, id: :answer_correct %>
 </p>

 <div class="actions">
   <p><%= form.submit %></p>
 </div>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>New Answer</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form' %>
<%= link_to 'Back', admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1>New Answer</h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form' %>
<%= link_to 'Back', admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1>Question</h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <b>Answer:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Back', admin_question_path(@answer.question) %>